{
 "title": "JVM & DB Metrics (Micrometer)",
 "description": "Dashboard for Micrometer and influx DB instrumented applications that are persisted in Influx DB (Java, Spring Boot)\r\n",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Application",
    "label": "Application",
    "query": "SHOW TAG VALUES WITH KEY = \"application\""
   },
   {
    "name": "Environment",
    "label": "Environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\""
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_start_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A /$B * 100", "type": "math" }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B * 100", "type": "math" }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "HTTP",
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "HTTP 5XX Errors",
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "HTTP - 5xx",
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "status::tag", "operator": "=~", "value": "/5../" }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "HTTP Response time Mean",
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "HTTP - AVG",
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "status::tag", "operator": "!~", "value": "/5../" }
     ]
    },
    {
     "alias": "HTTP Response time Max",
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "HTTP - AVG",
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "status::tag", "operator": "!~", "value": "/5../" }
     ]
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "memory_used",
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "area::tag", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "memory_max",
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "area::tag", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "memory_commited",
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "area::tag", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "memory_used",
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "area::tag", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "memory_max",
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "area::tag", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "memory_commited",
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "area::tag", "operator": "=", "value": "nonheap" }
     ]
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "memory_used",
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "memory_max",
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "memory_commited",
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_memory_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "System CPU",
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "system",
     "measurement": "system_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*100." ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "Process CPU",
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "system",
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*100." ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "System-1m",
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "system-1m",
     "measurement": "system_load_average_1m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "CPU",
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "system-1m",
     "measurement": "system_cpu_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Live",
     "expr": "jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "live",
     "measurement": "jvm_threads_live",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "Daemon",
     "expr": "jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "live",
     "measurement": "jvm_threads_daemon",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "Peak",
     "expr": "jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "live",
     "measurement": "jvm_threads_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "State: $tag_state",
     "expr": "jvm_threads_states_threads{application=\"$application\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "measurement": "jvm_threads_states",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "alias": "Level: $tag_level",
     "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "level::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{level}}",
     "measurement": "logback_events",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Open",
     "expr": "process_files_open_files{application=\"$application\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "open",
     "measurement": "process_files_open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "Max",
     "expr": "process_files_open_files{application=\"$application\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "open",
     "measurement": "process_files_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "Action: $tag_action",
     "expr": "rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "action::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{action}} ({{cause}})",
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Allocated",
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "allocated",
     "measurement": "jvm_gc_memory_allocated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "Promoted",
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "allocated",
     "measurement": "jvm_gc_memory_promoted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{application=\"$application\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "loaded",
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{application=\"$application\",instance=\"$instance\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "delta-1m",
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "repeat": "jvm_buffer_pool",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Used",
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_buffer_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "direct" }
     ]
    },
    {
     "alias": "Capacity",
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_buffer_total_capacity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "direct" }
     ]
    }
   ]
  },
  {
   "title": "Direct Buffers Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Used",
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_buffer_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "direct" }
     ]
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Used",
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_buffer_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "mapped" }
     ]
    },
    {
     "alias": "Capacity",
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_buffer_total_capacity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "mapped" }
     ]
    }
   ]
  },
  {
   "title": "Mapped Buffers Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Capacity",
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "jvm_buffer_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "mapped" }
     ]
    }
   ]
  },
  { "title": "DB Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Hikari Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Connections",
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "hikaricp_connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "Idle",
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "hikaricp_connections_idle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "Max",
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "hikaricp_connections_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "Min",
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "hikaricp_connections_min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    },
    {
     "alias": "Usage",
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "hikaricp_connections_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Hikari Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Active",
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "hikaricp_connections_active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Hikari Connections Timed Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Timed Out",
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "measurement": "hikaricp_connections_timeout",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "environment::tag", "operator": "=~", "value": "/^$Environment$/" }
     ]
    }
   ]
  }
 ]
}